Changes to gem5 Resources [gem5 Vision]
Gem5Vision/gem5 pull request #2
Opened 2023-05-13 00:35 UTC by kunpai

We added a config file to configs/
We changes resources in src/python/gem5/resources by adding an api folder with mongoclient and jsonclient
We also made corresponding changes to testing directory and resource python files to make it work with our new schema

2023-05-15 15:42 UTC, powerjg reviewed
Overall, this looks really good. @BobbyRBruce, I tagged you in one place. Otherwise, I think it would be best for you to spend your time looking at the testing code. I didn't look at the tests at all.

There's one "high-level" thing I don't like, though I guess I could be convinced it's ok. I don't like that you changed `disk_image` to `diskimage`. This seems like an arbitrary change that just adds to the diff and doesn't actually improve anything. I would prefer to keep the name `disk_image`.

Also, look through the diff and remove any whitespace-only changes.

Finally, what is the backwards compatibility story? Do we need to have a DB running or an entirely new json file ready before merging?

2023-05-15 15:42 UTC, powerjg commented on configs/gem5Resources.config.json
Shouldn't go in configs. A gem5 "config" is different than this file.

2023-05-15 15:42 UTC, powerjg commented on src/python/gem5/components/boards/kernel_disk_workload.py
> +    def _add_disk_to_board(self, diskimage: DiskImageResource) -> None:
Why did you change this variable name? Please revert unless absolutely necessary.

2023-05-15 15:42 UTC, powerjg commented on src/python/gem5/resources/api/client.py
> +                        f"Resource compatible with gem5 version: '{core.gem5Version}' not found.\n"
Line length.

2023-05-15 15:42 UTC, powerjg commented on src/python/gem5/resources/api/client.py
> +            if resource["resource_version"] == resource_version:
```suggestion
resource = next([resource for resource in resources if resource["resource_version"] == resource_version), None)
if not resource:
    raise ...
if core.gem5Version not in resource["gem5_versions"]:
    ...
```

I don't love the nestedness.

2023-05-15 15:42 UTC, powerjg commented on src/python/gem5/resources/api/client.py
> +                compatible_resources.append(resource)
```suggestion
        compatible_resources = [resource for resource in resources if core.gem5Version in resource["gem5_versions"]]
```

2023-05-15 15:42 UTC, powerjg commented on src/python/gem5/resources/api/client.py
> +            return resources
Add a comment about why you are returning *all* the resources here.

2023-05-15 15:42 UTC, powerjg commented on src/python/gem5/resources/api/client_wrapper.py
> +        / "configs/gem5Resources.config.json",
Do you mean for this filename to be hardcoded? If so, can you add more comments? Otherwise, it should be a variable (maybe an environment variable?)

Also, I don't think that we should use this file's location for hardcoding this config. @BobbyRBruce and I can think about the better way to do this.

2023-05-15 15:42 UTC, powerjg commented on src/python/gem5/resources/api/client_wrapper.py
> +):
Needs some documentation

2023-05-15 15:42 UTC, powerjg commented on src/python/gem5/resources/api/client_wrapper.py
> +clients = create_clients(config)
I'm a bit uncomfortable with this code running on import.

2023-05-15 15:42 UTC, powerjg commented on configs/example/gem5_library/riscvmatched-hello.py
This should be a separate change.

2023-05-15 15:42 UTC, powerjg commented on src/python/gem5/resources/api/jsonclient.py
> +    ) -> Dict[str, Union[str, Dict[str, str], List[str]]]:
I'm not sure the return type is correct here, but it's not a big deal. Maybe simply `Dict[str, Any]`

2023-05-15 15:42 UTC, powerjg commented on src/python/gem5/resources/api/jsonclient.py
> +        # getting all the resources with the given id from MongoDB
Typo with MongoDB here.

2023-05-15 15:42 UTC, powerjg commented on src/python/gem5/resources/api/mongoclient.py
> +import requests
As far as I can tell, this is *not* in python's standard library. See https://requests.readthedocs.io/en/latest/user/install/#install

That said... you can probably replace it with urllib2 or http. See https://www.reddit.com/r/Python/comments/o2qxwr/comparison_of_python_http_clients/

2023-05-15 15:42 UTC, powerjg commented on src/python/gem5/resources/api/mongoclient.py
> +            key=lambda x: list(map(int, x["resource_version"].split("."))),
You could also use this to sort by semantic versions. I don't have a strong preference, though.

https://stackoverflow.com/questions/2574080/sorting-a-list-of-dot-separated-numbers-like-software-versions

2023-05-15 15:42 UTC, powerjg commented on src/python/gem5/resources/api/client_wrapper.py
> +    database: Optional[str] = None,
I'm confused by this function's name. It's the same as `AbstractClient`, but it has a different signature. 

I suggest not having the same function names with different signatures.

2023-05-15 15:42 UTC, powerjg commented on src/python/gem5/resources/downloader.py
> -
Don't arbitrarily remove whitespace. (I'm surprised that black wasn't run)

2023-05-15 15:42 UTC, powerjg commented on src/python/gem5/resources/looppoint.py
> -
No whitespace changes.

2023-05-15 15:42 UTC, powerjg commented on tests/pyunit/stdlib/resources/pyunit_md5_utils_check.py
> -
whitespace....

2023-05-15 15:42 UTC, powerjg commented on src/python/gem5/resources/resource.py
> +# from m5.util import warn, fatal
Don't comment things out. Delete them or keep them.

2023-05-15 15:42 UTC, powerjg commented on src/python/gem5/resources/resource.py
> +    database: Optional[str] = None,
Needs to be documented in the docstring.

2023-05-15 15:42 UTC, powerjg commented on src/python/gem5/resources/resource.py
> +    resource_json = get_resource_obj(
Should this now be something like `resource_data` since it's just a dictionary?

2023-05-15 15:42 UTC, powerjg commented on .gitignore
Should be in a separate change.

2023-05-15 15:42 UTC, powerjg requested changes
Overall, this looks really good. @BobbyRBruce, I tagged you in one place. Otherwise, I think it would be best for you to spend your time looking at the testing code. I didn't look at the tests at all.

There's one "high-level" thing I don't like, though I guess I could be convinced it's ok. I don't like that you changed `disk_image` to `diskimage`. This seems like an arbitrary change that just adds to the diff and doesn't actually improve anything. I would prefer to keep the name `disk_image`.

Also, look through the diff and remove any whitespace-only changes.

Finally, what is the backwards compatibility story? Do we need to have a DB running or an entirely new json file ready before merging?

2023-05-15 21:40 UTC, kunpai commented on configs/gem5Resources.config.json
Where is a good place we can place it?

2023-05-16 02:20 UTC, powerjg commented on configs/gem5Resources.config.json
The root would be a better location. However, Bobby and I need to chat about how to resolve that location from the stdlib. I don't like the `__file_path__.parent.parent.parent...` thing.

2023-05-18 20:41 UTC, BobbyRBruce reviewed
I haven't reviewed the tests (i'll do so another time).

Even though this looks like a lot of criticism, this is really excellent work. Just a couple more iterations of this and I think we'll be ready to incorporate into the gem5 project.

2023-05-18 20:41 UTC, BobbyRBruce commented on .gitignore
> +
Is there a good reason to have an empty line here?

2023-05-18 20:41 UTC, BobbyRBruce commented on configs/gem5Resources.config.json
> +}
This is petty in the extreme but it's pretty standard to have a newline character at the end of a file. See here for why: https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

2023-05-18 20:41 UTC, BobbyRBruce commented on src/python/gem5/resources/api/client.py
> +                "Resource versions can be found at: "
Expand this warning a little bit. As is written it doesn't state what this means for your simulation run.

I'd say: "Resource {resource['id']} version {resource_version} is not known to be compatible with gem5 version {core.gem5Version}. This may cause problems with your simulation. This resource's compatibility with different gem5 versions can be found here: ..."

This makes it clear that this might be dangerous but the simulator isn't going to stop you.

2023-05-18 20:41 UTC, BobbyRBruce commented on src/python/gem5/resources/api/client.py
> +    def _get_compatible_resources(self, resources: List) -> List:
I'd change this function to return an empty list if no compatible resources are found in the list. I know why you're doing this but I feel like this function should be simple and correspond to its name.

For example, if all the resources in the list are compatible with the current version of gem5, then this function's return is identical to the case where none of them are. We're losing information.

2023-05-18 20:41 UTC, BobbyRBruce commented on src/python/gem5/resources/api/client.py
> +        Returns a list of compatible resources with the given gem5 version.
We're phrasing here "given gem5 version". I'd rephrase to "current gem5 version".

2023-05-18 20:41 UTC, BobbyRBruce commented on src/python/gem5/resources/api/client.py
> +    def _search_version(self, resources: List, resource_version: str) -> dict:
This function should be merged into `_get_compatible_resources`. Perhaps this function can be:

```
def _get_resources_comatible(resources: : List[dict], resource_version: str =core.gem5Version ) -> List[dict]:
```

It will filter the list to those only with a compatible version.

2023-05-18 20:41 UTC, BobbyRBruce commented on src/python/gem5/resources/api/client.py
> +                f"Resource {resources[0]['id']} with version '{resource_version}'"
I think these warnings/exceptions should be put elsewhere. In this function, as it it written, we cannot assume all the resources passed have the same id. This function could, theoretically, be used to filter all the resources we have to the list of those with known compatibility (this may be useful at some point).

I would probably opt for putting these in a separate function with a signature like:

```
check_resource_version_capatibility(resource: dict, gem5_version: str = core.gem5Version) ->None
```

You could call it when you want to run these checks.

2023-05-18 20:41 UTC, BobbyRBruce commented on src/python/gem5/resources/api/client.py
> +    def _sort_resources_by_version(self, resources: List) -> List:
In keeping with my other comments, this signature here does not restrict a user from inputting a list of resources with different IDs. I'd change this function to be `_sort_resources`, which sorts resources based first on id, then on version.

2023-05-18 20:41 UTC, BobbyRBruce commented on src/python/gem5/resources/api/client_wrapper.py
> +    for resource in config["resources"]:
Is it too late to call call this something like "clients" instead of "resources". Needless to say, the word "resources" here is getting overused.

2023-05-18 20:41 UTC, BobbyRBruce commented on src/python/gem5/resources/api/client_wrapper.py
> +):
Add return type here 'Dict'

2023-05-18 20:41 UTC, BobbyRBruce commented on src/python/gem5/resources/api/client_wrapper.py
> +        database = list(clients.keys())[0]
I'm not sure if we have discussed this before, but is this the behavior we want? If the user doesn't specify the database here, we just assume we're looking in the first one.

How about this: we don't have a "database" field, and we always search all our clients for instances of a resource. We throw an exception if there are duplicates (same id and version). Would that work?

2023-05-18 20:41 UTC, BobbyRBruce commented on src/python/gem5/resources/api/jsonclient.py
> +import requests
As Jason said in the other file, I don't think we can use requests.

2023-05-18 20:41 UTC, BobbyRBruce commented on src/python/gem5/resources/api/jsonclient.py
> +    def get_resource_obj_from_client(
It seems to me like a simpler way of doing this would be to have an abstract function in `AbstractClient` called `get_resources_by_id(id: str)`. Then have `get_resource_obj_from_client` implemented in `AbstractClient` (which calls `get_resources_by_id`).

This would mean `JSONClient` and `MongoClient` would only need to implement `get_resources_by_id` which seems to be the only thing that truly differs between the two clients.

2023-05-18 20:41 UTC, BobbyRBruce commented on src/python/gem5/resources/downloader.py
> -
You've deleted a line here for no real reason. Avoid doing stuff like this. It just makes the change a bit messier than it needs to be.

2023-05-18 20:41 UTC, BobbyRBruce commented on src/python/gem5/resources/downloader.py
> +from python.gem5.resources.api.client_wrapper import get_resource_obj
Within the stdlib you should use relative imports. So in this case, `from .api.client_wrapper import get_resource_obj`

2023-05-18 20:41 UTC, BobbyRBruce commented on src/python/gem5/resources/looppoint.py
> +
This to me shows you probably don't have our pre-commit checks installed. It will automatically detect and remove unnecessary whitespace like this. Run `./util/pre-commit-install.sh` to do so

2023-05-18 20:41 UTC, BobbyRBruce commented on src/python/gem5/resources/workload.py
> -
I'll only say this once more, because there's numerous parts this happens, but please don't remove lines randomly like this. The commit/pull-request should only be focused on adding/removing code as needed.

2023-05-18 20:41 UTC, BobbyRBruce commented on src/python/SConscript
> +PySource('gem5.resources.api', 'gem5/resources/api/client_wrapper.py')
I think "api" is too generic. Can we call this directory "client_api" instead?

2023-05-18 20:41 UTC, BobbyRBruce commented on src/python/gem5/resources/downloader.py
> +        resource_obj = get_resource_obj(
I'm getting a bit confused by this: is this returning a resource object (i.e. a full implementation such as `BinaryResource`, or a dictionary representing the JSON?). It's really not clear.

From what I can see in the rest of this file, it's just a JSON representation of the object, so why the change of this function name and variable. This seems pointless.

2023-05-18 20:41 UTC, BobbyRBruce commented on src/python/gem5/resources/api/client_wrapper.py
> +            / "configs/gem5Resources.config.json",
There is an issue here of where the config file should exist, how it should be used, and how a user interacts with it. I discussed this with Jason and I think you should do the following:

1. The config file should be called "gem5-config.json".
2. It should be moved to "src/python".
3. This configs file should be compiled into the binary (me and Jason's answer to the question "but how do I do this?" is "🤷‍♂️" , but we _think_ it should be possible...)
4. This compiled-in config file config file will serve as the default values for those fields. In addition to this the user can set an environment variable to specify their own "gem5-config.json" file to override this. (e.g. "GEM5_CONFIG="/home/bbruce/my-config.json" ./build/ALL/gem5.opt ...` should allow for loading of the "my-config.json" file, replacing the compiled in version).
5. If there is a "gem5-config.json" in the current working directory, gem5 should use this.

4 and 5 should be optional stretch-goals for now (i.e., only do them if you've got nothing better to do and want to). but I think you should try to do 1, 2, and 3.

2023-05-22 06:35 UTC, merged